int   mpfi_set        (mpfi_ptr, mpfi_srcptr);
int   mpfi_set_fr   (mpfi_ptr, mpfr_srcptr);
int   mpfi_init        (mpfi_ptr);
int   mpfi_clear        (mpfi_ptr);
int   mpfi_init_set        (mpfi_ptr, mpfi_srcptr);
int   mpfi_init_set_fr   (mpfi_ptr, mpfr_srcptr);
int mpfi_diam_abs(mpfr_ptr, mpfi_srcptr);
int mpfi_diam_rel(mpfr_ptr, mpfi_srcptr);
int mpfi_diam(mpfr_ptr, mpfi_srcptr);
int mpfi_mag(mpfr_ptr, mpfi_srcptr);
int mpfi_mig(mpfr_ptr, mpfi_srcptr);
int mpfi_mid (mpfr_ptr, mpfi_srcptr);
int   mpfi_add        (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int   mpfi_sub        (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int   mpfi_mul        (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int   mpfi_div        (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int   mpfi_add_fr  (mpfi_ptr, mpfi_srcptr, mpfr_srcptr);
int   mpfi_sub_fr  (mpfi_ptr, mpfi_srcptr, mpfr_srcptr);
int   mpfi_fr_sub  (mpfi_ptr, mpfr_srcptr, mpfi_srcptr);
int   mpfi_mul_fr  (mpfi_ptr, mpfi_srcptr, mpfr_srcptr);
int   mpfi_div_fr  (mpfi_ptr, mpfi_srcptr, mpfr_srcptr);
int   mpfi_fr_div  (mpfi_ptr, mpfr_srcptr, mpfi_srcptr);
int   mpfi_neg        (mpfi_ptr, mpfi_srcptr);
int   mpfi_sqr        (mpfi_ptr ,mpfi_srcptr);
int   mpfi_inv        (mpfi_ptr, mpfi_srcptr);
int   mpfi_sqrt       (mpfi_ptr, mpfi_srcptr);
int   mpfi_abs        (mpfi_ptr, mpfi_srcptr);
int mpfi_log  (mpfi_ptr, mpfi_srcptr);
int mpfi_exp  (mpfi_ptr, mpfi_srcptr);
int mpfi_exp2 (mpfi_ptr, mpfi_srcptr);
int mpfi_cos  (mpfi_ptr, mpfi_srcptr);
int mpfi_sin  (mpfi_ptr, mpfi_srcptr);
int mpfi_tan  (mpfi_ptr, mpfi_srcptr);
int mpfi_acos (mpfi_ptr, mpfi_srcptr);
int mpfi_asin (mpfi_ptr, mpfi_srcptr);
int mpfi_atan (mpfi_ptr, mpfi_srcptr);
int mpfi_cosh (mpfi_ptr, mpfi_srcptr);
int mpfi_sinh (mpfi_ptr, mpfi_srcptr);
int mpfi_tanh (mpfi_ptr, mpfi_srcptr);
int mpfi_acosh (mpfi_ptr, mpfi_srcptr);
int mpfi_asinh (mpfi_ptr, mpfi_srcptr);
int mpfi_atanh (mpfi_ptr, mpfi_srcptr);
int mpfi_log1p (mpfi_ptr, mpfi_srcptr);
int mpfi_expm1 (mpfi_ptr, mpfi_srcptr);
int mpfi_log2 (mpfi_ptr, mpfi_srcptr);
int mpfi_log10 (mpfi_ptr, mpfi_srcptr);
int    mpfi_is_pos_default          (mpfi_srcptr);
int    mpfi_is_nonneg_default       (mpfi_srcptr);
int    mpfi_is_neg_default          (mpfi_srcptr);
int    mpfi_is_nonpos_default       (mpfi_srcptr);
int    mpfi_is_zero_default         (mpfi_srcptr);
int    mpfi_is_strictly_neg_default (mpfi_srcptr a);
int    mpfi_is_strictly_pos_default (mpfi_srcptr a);
int    mpfi_cmp_default      (mpfi_srcptr,mpfi_srcptr);
int    mpfi_cmp_fr_default (mpfi_srcptr,mpfr_srcptr);
int mpfi_has_zero (mpfi_srcptr);
int mpfi_nan_p (mpfi_srcptr);
int mpfi_inf_p (mpfi_srcptr);
int mpfi_bounded_p (mpfi_srcptr);
int   mpfi_get_left   (mpfr_ptr,mpfi_srcptr);
int   mpfi_get_right  (mpfr_ptr,mpfi_srcptr);
int   mpfi_put        (mpfi_ptr,mpfi_srcptr);
int   mpfi_put_fr     (mpfi_ptr,mpfr_srcptr);
int   mpfi_interv_fr  (mpfi_ptr,mpfr_srcptr,mpfr_srcptr);
int   mpfi_is_strictly_inside   (mpfi_srcptr,mpfi_srcptr);
int   mpfi_is_inside        	(mpfi_srcptr, mpfi_srcptr);
int   mpfi_is_inside_fr   	(mpfr_srcptr,mpfi_srcptr);
int   mpfi_is_empty         (mpfi_srcptr);
int   mpfi_intersect        (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int   mpfi_union            (mpfi_ptr, mpfi_srcptr, mpfi_srcptr);
int  mpfi_increase         (mpfi_ptr,mpfr_srcptr);
int mpfi_bisect(mpfi_ptr, mpfi_ptr, mpfi_srcptr);
